version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    volumes:
      - .:/app
    environment:
      - ENV=development